### ISSUE TITLE
Service not defined in Resolver

### ISSUE THREAD

**Issue by kvarela** [19majkel94/type-graphql#118]
**Describe the bug**
Thanks so much for this awesome lib. I really want to use it, but am having a lot of difficulty in my serverless environment. I followed your guides, but when I try to access my service from my resolver, it is undefined. Maybe I'm just missing a step. I don't really understand when the service is actually passed in to the resolver.

**To Reproduce**
Here's my handler:
```
exports.handler = async (event: any, context: any, callback: any) => {
    const database = new Database()
    const connection: Connection = await database.getConnection()

    // Initialize services
    const userService = new UserService(connection)
    const authService = new AuthService(userService)

    const schema = await buildSchema({ resolvers: [UserResolver] });

    context = {
        headers: event.headers,
        functionName: context.functionName,
        event,
        context,
        authService,
        userService
    }

    const apolloServerConfig: Config = {
        schema,
        context
    }

    const apolloServer = new ApolloServer(apolloServerConfig)

    const handler = apolloServer.createHandler({
        cors: {
            origin: '*',
            credentials: true,
        },
    })

    return handler(event, context, callback)
};
```

Here's the important snippet of my Object:
```
@Entity()
@ObjectType()
export class User {
    @PrimaryGeneratedColumn("uuid")
    @Field(() => ID)
    public id!: string
```

And here's my resolver:
```
@Resolver()
export class UserResolver {
    constructor(private userService: UserService) { }

    @Query(returns => User)
    public async user(@Arg(`id`) id: string) {
        const user = await this.userService.findById(id)

        if (!user) {
            throw new Error("User not found")
        }

        return user
    }
}
```

**Expected behavior**
I expect this to magically work, but am getting the error:
"Cannot read property 'findById' of undefined"

**Logs**
```
"TypeError: Cannot read property 'findById' of undefined",
            "    at UserResolver.<anonymous> (/Users/home/roam/backend/.build/src/graphql/resolvers/UserResolver.js:32:49)",
            "    at Generator.next (<anonymous>)",
            "    at /Users/home/roam/backend/.build/src/graphql/resolvers/UserResolver.js:19:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/Users/home/roam/backend/.build/src/graphql/resolvers/UserResolver.js:15:12)",
            "    at UserResolver.user (/Users/home/roam/backend/.build/src/graphql/resolvers/UserResolver.js:31:16)",
            "    at Object.<anonymous> (/Users/home/roam/backend/node_modules/type-graphql/resolvers/create.js:24:45)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/Users/home/roam/backend/node_modules/type-graphql/resolvers/create.js:4:58)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
```

**Enviorment (please complete the following information):**
 - OS: Serverless running locally on my Mac
 - Node 6.10
 - Package version 0.12.3
 - TypeScript version 2.9.2

Any help much appreciated!

**Comment by 19majkel94** [comment]
```ts
	// Initialize services
    const userService = new UserService(connection)
    const authService = new AuthService(userService)

    const schema = await buildSchema({ resolvers: [UserResolver] });
```
This won't work. You need to provide a DI container that will resolver your dependencies defined in constructor:
https://19majkel94.github.io/type-graphql/docs/dependency-injection.html

You can use `TypeDI`, `injection.js` or whatever you want. Even an custom one - simple and naive solution:
```ts
useContainer({
  get(SomeClass: any) {
	if (SomeClass=== UserResolver) {
      return new UserResolver(userService);
    }
    return new SomeClass();
  }
});
```

**Comment by kvarela** [comment]
Thanks so much, I think I was able to solve by using typedi. Now, on to:
```Error: Schema must contain unique named types but contains multiple types named "User".```

I know there's another issue describing how to work around this, but it was difficult for me to digest. I will take another stab at it, but if you have any clear direction, that would be amazing. I really want to get this working!
