### ISSUE TITLE
What I am doing wrong with the InputType

### ISSUE THREAD

**Issue by nodejayes** [19majkel94/type-graphql#204]
Hello Guys,

I want to use a Input Type for my Mutation in a Resolver.

First i declare a ObjectType

```
import {Column, CreatedAt, DefaultScope, DeletedAt, Model, Sequelize, Table, UpdatedAt} from 'sequelize-typescript';
import {Field, ID, ObjectType}                                                          from 'type-graphql';

@DefaultScope({})
@Table({
  timestamps: true,
  version: true,
  comment: 'holds the Users Bank Accounts',
})
@ObjectType()
export class BankAccount extends Model<BankAccount> {
  @Column({
    field: 'id',
    type: Sequelize.UUID,
    allowNull: false,
    defaultValue: Sequelize.UUID,
    primaryKey: true,
  })
  @Field(type => ID)
  Id: string;

  @Column({
    field: 'title',
    type: Sequelize.STRING(255),
    allowNull: false,
    validate: {
      min: 3,
      max: 255
    }
  })
  @Field(type => String)
  Title: string;

  @Column({
    field: 'user_id',
    type: Sequelize.UUID,
    allowNull: false,
    validate: {
      isUUID: 4,
    }
  })
  @Field(type => ID)
  UserId: string;

  @CreatedAt
  @Field(type => Date)
  CreationDate: Date;

  @UpdatedAt
  @Field(type => Date)
  UpdatedOn: Date;

  @DeletedAt
  @Field(type => Date)
  DeletionDate: Date;
}
```

Then i have create a Resolver with a Query and a Mutation.

```
@Resolver()
export class BankAccountResolver {

  @Query(returns => [BankAccount])
  async getBankAccounts() {
    return await BankAccount.findAll();
  }

  @Mutation()
  async createBankAccount(
    @Arg('data') newBankAccountData: CreateBankAccountArgument
  ): Promise<BankAccount> {
    return await BankAccount.create(newBankAccountData);
  }
}
```

Then i created the InputType for the Mutation

```
import {Field, ID, InputType} from 'type-graphql';

@InputType()
export class CreateBankAccountArgument {
  @Field(type => String)
  Title: string;

  @Field(type => ID)
  UserId: string;
}
```

Then i Build the Schema and only register the Resolver Class

```
import {buildSchemaSync}     from 'type-graphql';

buildSchemaSync({
  resolvers: [BankAccountResolver],
  emitSchemaFile: true,
});
```

After that i get the Following Error

```
C:\git\financer\node_modules\type-graphql\helpers\findType.js:10
        metadataDesignType = reflectedType[parameterIndex];
                                          ^

TypeError: Cannot read property '0' of undefined
    at Object.findType (C:\git\financer\node_modules\type-graphql\helpers\findType.js:10:43)
    at Object.getParamInfo (C:\git\financer\node_modules\type-graphql\helpers\params.js:9:49)
    at Arg (C:\git\financer\node_modules\type-graphql\decorators\Arg.js:9:159)
    at C:\git\financer\dist\models\bank-account\resolver.js:9:37
    at DecorateProperty (C:\git\financer\node_modules\reflect-metadata\Reflect.js:553:33)
    at Object.decorate (C:\git\financer\node_modules\reflect-metadata\Reflect.js:123:24)
    at __decorate (C:\git\financer\dist\models\bank-account\resolver.js:4:92)
    at Object.<anonymous> (C:\git\financer\dist\models\bank-account\resolver.js:37:1)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\git\financer\dist\boot.js:15:20)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
```

Waht I am doing wrong here? When I comment out my Mutation i can build the GraphQl Schema and Request it with the apollo Server Playground but with Mutation the Schema not compiles...

**Comment by 19majkel94** [comment]
At first look, you have to provide `@Mutation(returns => BankAccount)` but the error is about the argument of the mutation.

So I bet you haven't setup your project correctly:
https://github.com/19majkel94/type-graphql#how-to-use
`reflect-metadata` and `emitDecoratorMetadata` is a must have to make it work without providing `@Arg('data', type => CreateBankAccountArgument)`.

If it doesn't fix your issue, I will try to launch your code later and will figure out what's going on.

**Comment by nodejayes** [comment]
Thank you for the hint I forgot to include emitDecoratorMetadata in my tsconfig.json, now everything is working fine.
