### ISSUE TITLE
Input type that subclassing abstract type trigger unknown error

### ISSUE THREAD

**Issue by below-1** [19majkel94/type-graphql#227]
**Describe the bug**
Input type that extends some abstract class trigger an error when used in Resolver.

**To Reproduce**

##### TestItemAbstract.ts
```typescript
import { Field, InterfaceType, Int, Float } from 'type-graphql';

@InterfaceType()
export abstract class TestItemAbstract {
  @Field()
  name: string;

  @Field(type => Int)
  age: number;

  @Field(type => Float)
  weight: number;
}
```

##### TestItem.ts
```typescript
import { TestItemAbstract } from "./TestItemAbstract";
import { Int, Field, ObjectType } from "type-graphql";

@ObjectType({ implements: TestItemAbstract })
export class TestItem extends TestItemAbstract {
  @Field(type => Int)
  id: number;
}
```

##### TestItemInput.ts
```typescript
import { InputType } from "type-graphql";
import { TestItemAbstract } from "./TestItemAbstract";

@InputType()
export class TestItemInput extends TestItemAbstract {
  
}
```

And the resolver
##### TestItemResolver.ts
```typescript
import { Resolver, Mutation, Arg } from "type-graphql";
import { TestItem } from "../types/TestItem";
import { TestItemInput } from "../types/TestItemInput";

@Resolver(of => TestItem)
export class TestItemResolver {
  @Mutation(returns => TestItem)
  async createTestItem(@Arg("testItemInput") testItemInput: TestItemInput) {
    const result = new TestItem();
    result.id = 1;
    result.age = 12;
    result.weight = 12.0;
    result.name = 'something';
    return await result;
  }
}
```

**Expected behavior**

**Logs**
```
(node:5275) UnhandledPromiseRejectionWarning: Error: Generating schema error
    at Function.<anonymous> (/home/you/Project11/typegraphql-play/node_modules/type-graphql/schema/schema-generator.js:18:23)
    at Generator.next (<anonymous>)
    at fulfilled (/home/you/Project11/typegraphql-play/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at Function.Module.runMain (module.js:695:11)
    at Object.<anonymous> (/home/you/Project11/typegraphql-play/node_modules/ts-node/src/bin.ts:157:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
(node:5275) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated eitherby throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:5275) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Enviorment (please complete the following information):**
 - OS: Ubuntu 16
 - Node: v8.11.4
 - Package version: 0.16.0
 - TypeScript: 3.2.2

**Additional context**

**Comment by 19majkel94** [comment]
Try to catch the error and use console.log

**Comment by below-1** [comment]
Okay after try catch it, I got detailed error like this
```
...
  details:
   [ { Input Object type TestItemInput must define one or more fields.
    at SchemaValidationContext.reportError (/home/you/Project11/typegraphql-play/node_modules/graphql/type/validate.js:94:19)
    at validateInputFields (/home/you/Project11/typegraphql-play/node_modules/graphql/type/validate.js:630:13)
    at validateTypes (/home/you/Project11/typegraphql-play/node_modules/graphql/type/validate.js:290:9)
    at validateSchema (/home/you/Project11/typegraphql-play/node_modules/graphql/type/validate.js:54:3)
    at graphqlImpl (/home/you/Project11/typegraphql-play/node_modules/graphql/graphql.js:57:61)
    at /home/you/Project11/typegraphql-play/node_modules/graphql/graphql.js:32:223
    at new Promise (<anonymous>)
    at Object.graphql (/home/you/Project11/typegraphql-play/node_modules/graphql/graphql.js:30:10)
    at Function.<anonymous> (/home/you/Project11/typegraphql-play/node_modules/type-graphql/schema/schema-generator.js:16:48)
    at Generator.next (<anonymous>)
       message: 'Input Object type TestItemInput must define one or more fields.' } ] }
```
Seems like it need at least one field in InputType.
So I change `TestItemInput.ts`, provide additional dummy field
```typescript
@InputType()
export class TestItemInput extends TestItemAbstract {
  @Field()
  dummyField: string;
}
```

##### It works.

**Comment by below-1** [comment]
Is this intended behaviour?
