### ISSUE TITLE
Add implements to InputType

### ISSUE THREAD

**Issue by baronTommy** [19majkel94/type-graphql#299]
**Is your feature request related to a problem? Please describe.**
```ts
@InputType({ implements: IFoo })
```

**Comment by 19majkel94** [comment]
@baronTommy 
Unfortunatelly, GraphQL spec doesn't support implementing interfaces by input types. Only object types can implement graphql interfaces:
```graphql
type Foo implements IFoo & IBar {
  # ...
}
```

However, you can use TS interfaces for achieving type safety:
```ts
interface IFoo {
  foo: string;
}

@InputType()
class FooInput implements IFoo {
  @Field()
  foo: string;
}
```

**Comment by baronTommy** [comment]
```ts
@InputType()
class AddTask {
  @Field()
  title: string;

  @Field()
  body?: string;
}

@InputType()
class UpdateTask {
  @Field()
  id: number;

  @Field()
  title: string;

  @Field()
  body?: string;
}
```

↓   
Without duplication  
I want to do this  
If you can not  
I give up  🍎  
↓

```ts
@InterfaceType()
abstract class IBase {
  @Field()
  title: string;

  @Field()
  body?: string;
}

@InputType({ implements: IBase })
class AddTask {
}


@InputType({ implements: IBase })
class UpdateTask {
  @Field()
  id: number;
}
```

**Comment by 19majkel94** [comment]
@baronTommy Just use `extends` and inheritance:

```ts
@InterfaceType()
abstract class IBase {
  @Field()
  title: string;

  @Field()
  body?: string;
}

@InputType()
class UpdateTask extends IBase {
  @Field()
  id: number;
}
```

You can see it working in examples:

https://github.com/19majkel94/type-graphql/blob/ad9ecc19f08062a43c2e7d4d0b5fc1bbac6ccee5/examples/interfaces-inheritance/employee/employee.input.ts#L5-L9

**Comment by baronTommy** [comment]
👀
type-graphql/examples/interfaces-inheritance/employee/employee.input.ts


Is it bad usage?
```ts
@InterfaceType()
abstract class IBase {
  @Field()
  title: string;

  @Field()
  body?: string;
}

@InputType()
class UpdateTask2 extends IBase {
  @Field()
  id: number;
}

@InputType()
class AddTask2 extends IBase {
}
```

```bash
(node:39056) UnhandledPromiseRejectionWarning: Error: Generating schema error
    at Function.<anonymous> (/Volumes/workspace/todo/server/node_modules/type-graphql/dist/schema/schema-generator.js:19:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Volumes/workspace/todo/server/node_modules/tslib/tslib.js:104:62)
(node:39056) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:39056) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by 19majkel94** [comment]
> Is it bad usage?

Yes, it has to be an input type, not an interfaces type, as GraphQL distinguishes output types (interfaces) from input types (inputs) and you can't mix them.

Please read the examples and docs carefully and ask community for help on chat:
https://gitter.im/type-graphql/Lobby
