### ISSUE TITLE
Mutations/Input types break schema creation in AWS

### ISSUE THREAD

**Issue by orantwolinkme** [19majkel94/type-graphql#345]
**Describe the bug**
Adding mutations/input types to the schema causes the schema creation to fail when deployed to AWS lambda. The stack trace/error message don't contain any details:

`module initialization error: Error
at invariant (/var/task/node_modules/graphql/jsutils/invariant.js:21:11)
at typeMapReducer (/var/task/node_modules/graphql/type/schema.js:299:57)
at typeMapReducer (/var/task/node_modules/graphql/type/schema.js:295:12)
at Array.reduce (<anonymous>)
at typeMapReducer (/var/task/node_modules/graphql/type/schema.js:327:38)
at Array.reduce (<anonymous>)
at new GraphQLSchema (/var/task/node_modules/graphql/type/schema.js:145:28)
at Function.generateFromMetadataSync (/var/task/node_modules/type-graphql/dist/schema/schema-generator.js:31:24)
at Object.buildSchemaSync (/var/task/node_modules/type-graphql/dist/utils/buildSchema.js:22:55)
at Object.<anonymous> (/var/task/src/graphql.js:1:2604)`

**To Reproduce**
See repo with instructions how to reproduce https://github.com/orantwolinkme/type-graphql

**Expected behavior**
1. Schema creation in AWS lambda should work correctly with mutations/input types
2. A descriptive error message 

**Enviorment (please complete the following information):**
 - AWS Lambda
 - Node 8.10
 - Package version 0.17.4
 - TypeScript version 3.4.5

**Comment by 19majkel94** [comment]
I bet that the problem is with transpiliing the code using a webpack.

Are you able to reproduce the issue not using the AWS but only the webpack config used by it?
Without debugging possibility I'm afraid I can do nothing about it 😞

**Comment by orantwolinkme** [comment]
It is a webpack issue. In the code I uploaded in webpack.config.js there are settings for mode and devtool:
```   
    mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
    devtool: slsw.lib.webpack.isLocal
        ? 'cheap-module-eval-source-map'
        : 'source-map',
```

The setting that's breaking it is devtool using 'source-map' when not deployed locally

Changing devtool setting to:
```
    devtool: 'cheap-module-eval-source-map',
```
works

**Comment by orantwolinkme** [comment]
The call stack when it fails is:
```
"[
  "Error: Schema must contain uniquely named types but contains multiple types named \"c\".",
  "at invariant (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\graphql\\jsutils\\invariant.js:21:11)",
  "at typeMapReducer (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\graphql\\type\\schema.js:299:57)",
  "at typeMapReducer (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\graphql\\type\\schema.js:295:12)",
  "at Array.reduce (<anonymous>)",
  "at typeMapReducer (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\graphql\\type\\schema.js:327:38)",
  "at Array.reduce (<anonymous>)",
  "at new GraphQLSchema (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\graphql\\type\\schema.js:145:28)",
  "at Function.generateFromMetadataSync (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\type-graphql\\dist\\schema\\schema-generator.js:31:24)",
  "at Object.buildSchemaSync (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\type-graphql\\dist\\utils\\buildSchema.js:22:55)",
  "at Object.<anonymous> (C:\\Dev\\Learning\\type-graphql-minimal\\.webpack\\service\\src\\graphql.js:1:2604)",
  "at n (C:\\Dev\\Learning\\type-graphql-minimal\\.webpack\\service\\src\\graphql.js:1:220)",
  "at C:\\Dev\\Learning\\type-graphql-minimal\\.webpack\\service\\src\\graphql.js:1:1019",
  "at Object.<anonymous> (C:\\Dev\\Learning\\type-graphql-minimal\\.webpack\\service\\src\\graphql.js:1:1028)",
  "at Module._compile (internal/modules/cjs/loader.js:701:30)",
  "at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)",
  "at Module.load (internal/modules/cjs/loader.js:600:32)",
  "at tryModuleLoad (internal/modules/cjs/loader.js:539:12)",
  "at Function.Module._load (internal/modules/cjs/loader.js:531:3)",
  "at Module.require (internal/modules/cjs/loader.js:637:17)",
  "at require (internal/modules/cjs/helpers.js:22:18)",
  "at Object.createHandler (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\serverless-offline\\src\\functionHelper.js:192:17)",
  "at handler (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\serverless-offline\\src\\index.js:624:40)",
  "at Object.internals.handler (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\hapi\\lib\\handler.js:101:51)",
  "at request._protect.run (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\hapi\\lib\\handler.js:32:23)",
  "at module.exports.internals.Protect.internals.Protect.run (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\hapi\\lib\\protect.js:60:12)",
  "at exports.execute (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\hapi\\lib\\handler.js:26:22)",
  "at each (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\hapi\\lib\\request.js:401:16)",
  "at iterate (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\items\\lib\\index.js:36:13)",
  "at done (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\items\\lib\\index.js:28:25)",
  "at internals.Auth.payload (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\hapi\\lib\\auth.js:235:16)",
  "at each (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\hapi\\lib\\request.js:401:16)",
  "at iterate (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\items\\lib\\index.js:36:13)",
  "at done (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\items\\lib\\index.js:28:25)",
  "at onParsed (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\hapi\\lib\\route.js:341:20)",
  "at Subtext.parse (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\hapi\\lib\\route.js:380:20)",
  "at next (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\subtext\\lib\\index.js:46:26)",
  "at Wreck.read (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\subtext\\lib\\index.js:243:16)",
  "at finish (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\wreck\\lib\\index.js:374:20)",
  "at wrapped (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\wreck\\node_modules\\hoek\\lib\\index.js:879:20)",
  "at module.exports.internals.Recorder.onReaderFinish (C:\\Dev\\Learning\\type-graphql-minimal\\node_modules\\wreck\\lib\\index.js:449:16)",
  "at Object.onceWrapper (events.js:277:13)",
  "at module.exports.internals.Recorder.emit (events.js:194:15)",
  "at module.exports.internals.Recorder.EventEmitter.emit (domain.js:459:23)",
  "at finishMaybe (_stream_writable.js:641:14)",
  "at endWritable (_stream_writable.js:649:3)",
  "at module.exports.internals.Recorder.Writable.end (_stream_writable.js:589:5)",
  "at IncomingMessage.onend (_stream_readable.js:651:10)",
  "at Object.onceWrapper (events.js:277:13)",
  "at IncomingMessage.emit (events.js:194:15)",
  "at IncomingMessage.EventEmitter.emit (domain.js:441:20)",
  "at endReadableNT (_stream_readable.js:1125:12)"
]"
```

**Comment by 19majkel94** [comment]
Ok, so the problem is with production webpack and code minification. You have to disable it.

**Comment by orantwolinkme** [comment]
That's what I'm doing for now. Is there going to be a fix for this or is it outside the scope of this project?

**Comment by hxdef2517** [comment]
@19majkel94 I got similar issue with sequelize and type-graphql during schema creation

```
(node:3715) UnhandledPromiseRejectionWarning: Error: Cannot determine GraphQL output type for genres
    at Function.getGraphQLOutputType (/SYS/PROJECT/WEB/PROJECT/node_modules/type-graphql/dist/schema/schema-generator.js:394:19)
    at objectType.fields.reduce (/SYS/PROJECT/WEB/PROJECT/node_modules/type-graphql/dist/schema/schema-generator.js:174:44)
    at Array.reduce (<anonymous>)
    at fields (/SYS/PROJECT/WEB/PROJECT/node_modules/type-graphql/dist/schema/schema-generator.js:168:56)
    at resolveThunk (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/definition.js:381:40)
    at defineFieldMap (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/definition.js:563:18)
    at GraphQLObjectType.getFields (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/definition.js:518:27)
    at typeMapReducer (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/schema.js:320:61)
    at typeMapReducer (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/schema.js:330:22)
    at typeMapReducer (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/schema.js:330:22)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/schema.js:145:28)
    at Function.generateFromMetadataSync (/SYS/PROJECT/WEB/PROJECT/node_modules/type-graphql/dist/schema/schema-generator.js:31:24)
    at Function.<anonymous> (/SYS/PROJECT/WEB/PROJECT/node_modules/type-graphql/dist/schema/schema-generator.js:16:33)
    at Generator.next (<anonymous>)
    at /SYS/PROJECT/WEB/PROJECT/node_modules/tslib/tslib.js:110:75

```

**Comment by 19majkel94** [comment]
> Is there going to be a fix for this

You can place the full name in the decorator - `@ObjectType("fullName")` - so it won't use the minified class names.

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒

**Comment by MichalLytek** [comment]
@leonetosoft I think that only class names are minified.
