### ISSUE TITLE
Cannot determine GraphQL output type

### ISSUE THREAD

**Issue by hxdef2517** [19majkel94/type-graphql#358]
**Describe the bug**
I decided to upgrade one of my projects with the latest version of type-graphql as well as the project framework as well. The project is built on NestJS and currently I have 0.17.4 version of type-graphql installed.

After upgrade I can't even start project because of the error stated in the title.

**My Model File for Sequelize Typescript:**

```
import {
    Table,
    Column,
    Model,
    DataType,
    HasMany
} from 'sequelize-typescript';

import { IDefineOptions } from 'sequelize-typescript/lib/interfaces/IDefineOptions';
import { SongWords } from '../song-words/song-words.entity';
import { ObjectType, Field, ID } from 'type-graphql';

const tableOptions: IDefineOptions = {
    timestamp: false,
    tableName: 'song'
} as IDefineOptions;

@Table(tableOptions)
@ObjectType()
export class Song extends Model<Song> {

    @Column({
        type: DataType.INTEGER(11),
        autoIncrement: true,
        allowNull: false,
        unique: true,
        primaryKey: true
    })
    @Field(type => ID)
    public id: number;

    @Column({
        type: DataType.INTEGER(11),
        allowNull: false,
        field: 'type_id'
    })
    @Field()
    public typeId: number;

    @Column({
        type: DataType.STRING(255),
        allowNull: false
    })
    @Field()
    public name: string;

    @HasMany(() => SongWords, { onDelete: 'cascade' }) 
    @Field(type => [SongWords])
    songWords: SongWords[];
}
```

The other project models are kinda look similar but only this causing the error. 

**Error log:**
```
(node:3715) UnhandledPromiseRejectionWarning: Error: Cannot determine GraphQL output type for genres
    at Function.getGraphQLOutputType (/SYS/PROJECT/WEB/PROJECT/node_modules/type-graphql/dist/schema/schema-generator.js:394:19)
    at objectType.fields.reduce (/SYS/PROJECT/WEB/PROJECT/node_modules/type-graphql/dist/schema/schema-generator.js:174:44)
    at Array.reduce (<anonymous>)
    at fields (/SYS/PROJECT/WEB/PROJECT/node_modules/type-graphql/dist/schema/schema-generator.js:168:56)
    at resolveThunk (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/definition.js:381:40)
    at defineFieldMap (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/definition.js:563:18)
    at GraphQLObjectType.getFields (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/definition.js:518:27)
    at typeMapReducer (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/schema.js:320:61)
    at typeMapReducer (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/schema.js:330:22)
    at typeMapReducer (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/schema.js:295:12)
    at typeMapReducer (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/schema.js:330:22)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/SYS/PROJECT/WEB/PROJECT/node_modules/graphql/type/schema.js:145:28)
    at Function.generateFromMetadataSync (/SYS/PROJECT/WEB/PROJECT/node_modules/type-graphql/dist/schema/schema-generator.js:31:24)
    at Function.<anonymous> (/SYS/PROJECT/WEB/PROJECT/node_modules/type-graphql/dist/schema/schema-generator.js:16:33)
    at Generator.next (<anonymous>)
    at /SYS/PROJECT/WEB/PROJECT/node_modules/tslib/tslib.js:110:75
```

**Enviorment (please complete the following information):**
 - OS: OS X
 - Node v10.4.0
 - Package version 0.17.4
 - TypeScript version 3.2.4

tsconfig.json

```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2016",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "lib": ["es2016", "esnext.asynciterable"]
  },
  "exclude": ["node_modules"],
}
```

@nestjs/core 6.3.1

**Comment by hxdef2517** [comment]
Issue solved https://github.com/19majkel94/type-graphql/issues/188#issuecomment-459713490
