### ISSUE TITLE
Using typeof for Type args wont work

### ISSUE THREAD

**Issue by gotenxds** [19majkel94/type-graphql#392]
**Describe the bug**
Hello, I'm trying to create some kind of a default resolver, before moving to Typegraph I just did this buy creating a resolver on the fly, now with classes and types this does not seem to work.

**To Reproduce**
In my Type (Action) file:
```js
@ObjectType()
...
}

@ObjectType()
export class ActionResult {
...
}

@ArgsType()
export class ActionArgs {
...
}

```

In my Default Resolver  file:

```js

export default async (name) => {
  const plural = pluralize(name).toLowerCase();

  const { [name]: Entity, [`${name}Result`]: ResultEntity, [`${name}Args`]: EntityArgs } = await import(`../schemas/${name}`);

  @Resolver(Entity)
  class DefaultResolver {

    @Query(returns => ResultEntity)
    async [plural](@Args() args: typeof EntityArgs) {

    }
  }

  return DefaultResolver;
};

```

For this file I get the error: 
```

UnhandledPromiseRejectionWarning: Error: You need to provide explicit type for DefaultResolver#actions parameter #0 !
--


```
**Expected behavior**

To work as normal.

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occured.
```

(node:12576) UnhandledPromiseRejectionWarning: Error: You need to provide explicit type for DefaultResolver#actions parameter #0 !                at Object.findType (G:\devl\characters\node_modules\type-graphql\dist\helpers\findType.js:17:15)                                              at Object.getParamInfo (G:\devl\characters\node_modules\type-graphql\dist\helpers\params.js:9:49)                                             at G:\devl\characters\node_modules\type-graphql\dist\decorators\Args.js:9:120                                                                 at G:\devl\characters\server\apollo\resolvers\defaultResolverFactory.ts:12:37                                                                 at DecorateProperty (G:\devl\characters\node_modules\reflect-metadata\Reflect.js:553:33)                                                      at Object.decorate (G:\devl\characters\node_modules\reflect-metadata\Reflect.js:123:24)                                                       at __decorate (G:\devl\characters\server\apollo\resolvers\defaultResolverFactory.ts:4:92)                                                     at exports.default (G:\devl\characters\server\apollo\resolvers\defaultResolverFactory.ts:31:5)                                                at processTicksAndRejections (internal/process/task_queues.js:85:5)                                                                           at async Promise.all (index 0)                                                                                                                at Object.exports.createSchema (G:\devl\characters\server\apollo\resolvers\index.ts:8:16)                                                     at Object.exports.default (G:\devl\characters\server\apollo\apollo.ts:11:45)                                                                  at start (G:\devl\characters\server\index.ts:49:3)
--



```
**Enviorment (please complete the following information):**
 - OS: Windows 10
 - Node 12
 - Package version: latest
 - TypeScript version 3.4.1

**Comment by 19majkel94** [comment]
You can't use `typeof`, TypeGraphQL need a runtime value that is a class. For `@Args()` decorator you have to use a `@ArgsType()` class as a type.

```ts
@Args() args: EntityArgs
```
```ts
@ArgsType() 
export class EntityArgs {
  // ...fields here
}
```

**Comment by gotenxds** [comment]
I See, well I tried this originaly and it did not work:

```ts
@ArgsType() 
export class EntityArgs {
  // ...fields here
}
```

And in the code I tried

```ts

export default async (name) => {
  const plural = pluralize(name).toLowerCase();

  const { [name]: Entity, [`${name}Result`]: ResultEntity, [`${name}Args`]: EntityArgs } = await import(`../schemas/${name}`);

  @Resolver(Entity)
  class DefaultResolver {

    @Query(returns => ResultEntity)
    async [plural](@Args() args: EntityArgs) {

    }
  }

  return DefaultResolver;
};

```

But then I got the error `EntityArgs is a value but is being used as a type` which it is a type, but I guess Typescript cant see that as I dynamic import it.

**Comment by 19majkel94** [comment]
Can you create a minimal reproducible example? I think that the dynamic import with calculated prevent it from being statically typechecked. 

Why do you do this kind of weird importing the schema?

**Comment by 19majkel94** [comment]
Closing for a housekeeping purposes 🔒
